# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  config-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [85:34:22:3b:ac:e7:61:64:ff:e5:49:29:a4:65:9d:82

]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False
      - run:
          name: Run the ansible playbook
          command: |
            ansible-playbook -i inventory.txt playbook.yml

workflows:
  config-infrastructure:
    jobs:
      - config-infrastructure